Leilao/src/Leilao.UI.Site/Models/ErrorViewModel.cs
using System;

namespace Leilao.UI.Site.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Leilao/src/Leilao.UI.Site/Controllers/AuctionController.cs
using Leilao.ApplicationService.Interfaces;
using Leilao.ApplicationService.ViewModels.Request.Bid;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Leilao.UI.Site.Controllers {

    public class AuctionController : Controller {

        private readonly IBidApplicationService _bidApplicationService;
        private readonly IUserApplicationService _userApplicationService;
        private readonly IProductApplicationService _productApplicationService;

        public AuctionController(IBidApplicationService bidApplicationService, IUserApplicationService userApplicationService, IProductApplicationService productApplicationService) {
            _bidApplicationService = bidApplicationService;
            _userApplicationService = userApplicationService;
            _productApplicationService = productApplicationService;
        }


        [HttpGet]
        public async Task<IActionResult> CreateBid([FromQuery] string error) {

            ViewBag.Error = error;

            ViewBag.Produtos = await LoadProducts();
            ViewBag.Users = await LoadUsers();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBid(CreateBidRequestViewModel viewModel) {

            var ret = await _bidApplicationService.CreateBid(viewModel);

            if(ret == null)
                return RedirectToAction("CreateBid", "Auction", new { error = "Você nao pode oferecer um lance com esse valor, aumente e tente novamente!" });

            return RedirectToAction("BidList", "Auction");
        }

        [HttpGet]
        public async Task<IActionResult> BidList() {

            var list = await _bidApplicationService.GetAllBids();

            return View(list);
        }

        private async Task<SelectList> LoadProducts() {

            var allProducts = await _productApplicationService.GetAllProducts();

            Dictionary<Guid, string> dictProducts = new Dictionary<Guid, string>();

            allProducts.ForEach(x => {
                dictProducts.Add(x.Id, x.Name);
            });

            SelectList products = new SelectList(
                dictProducts.Select(x => new { Value = x.Key, Text = x.Value }),
                "Value",
                "Text"
            );

            return products;
        }

        private async Task<SelectList> LoadUsers() {

            var allUsers = await _userApplicationService.GetAllUsers();

            Dictionary<Guid, string> dictUsers = new Dictionary<Guid, string>();

            allUsers.ForEach(x => {
                dictUsers.Add(x.Id, x.Name);
            });

            SelectList users = new SelectList(
                dictUsers.Select(x => new { Value = x.Key, Text = x.Value }),
                "Value",
                "Text"
            );

            return users;
        }
    }
}

Leilao/src/Leilao.UI.Site/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Leilao.UI.Site.Models;

namespace Leilao.UI.Site.Controllers {
    public class HomeController : Controller {

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Leilao/src/Leilao.UI.Site/Controllers/ProductController.cs
using Leilao.ApplicationService.Interfaces;
using Leilao.ApplicationService.ViewModels.Request.Product;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Leilao.UI.Site.Controllers {

    public class ProductController : Controller {

        private readonly IProductApplicationService _productApplicationService;

        public ProductController(IProductApplicationService productApplicationService) {
            _productApplicationService = productApplicationService;
        }

        [HttpGet]
        public IActionResult CreateProduct() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateProduct(CreatePrductRequestViewModel viewModel) {

            await _productApplicationService.CreateProduct(viewModel);

            return RedirectToAction("Index", "Home");
        }

    }
}

Leilao/src/Leilao.UI.Site/Controllers/UserController.cs
using Leilao.ApplicationService.Interfaces;
using Leilao.ApplicationService.ViewModels.Request.User;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Leilao.UI.Site.Controllers {

    public class UserController : Controller {

        private readonly IUserApplicationService _userApplicationService;

        public UserController(IUserApplicationService userApplicationService) {
            _userApplicationService = userApplicationService;
        }

        [HttpGet]
        public IActionResult CreateUser() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser(CreateUserRequestViewModel viewModel) {

            await _userApplicationService.CreateUser(viewModel);

            return RedirectToAction("Index", "Home");
        }

    }
}

Leilao/src/Leilao.UI.Site/Views/Auction/BidList.cshtml
@model IEnumerable<Leilao.ApplicationService.ViewModels.Response.BidResponseViewModel>

@{
    ViewData["Title"] = "Lances";
}

<script src="~/js/site.js"></script>

<h1>Lances</h1>

<p>
    <a asp-action="CreateBid">Dar um lance</a>
</p>
<input type="text" id="inputSearch" onkeyup="myFunction()" placeholder="Procure por nome" class="form-group">
<table class="table" id="tableBids">
    <thead>
        <tr>
            <th>
                Produto
            </th>
            <th>
                Usuario do Lance
            </th>
            <th>
                Valor do Lance
            </th>
            <th>
                Valor Minimo
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PriceOffer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Price)
                </td>
            </tr>
        }
    </tbody>
</table>

Leilao/src/Leilao.UI.Site/Views/Auction/CreateBid.cshtml
@model Leilao.ApplicationService.ViewModels.Request.Bid.CreateBidRequestViewModel

@{
    ViewData["Title"] = "Dar lance";
}

<h1>Lance</h1>

<h4>De seu lance aqui</h4>
<hr />
<div class="text-danger">@ViewBag.Error</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateBid">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <label asp-for="IdProduct" class="control-label">Produto</label>
            <select asp-for="IdProduct" asp-items="ViewBag.Produtos" class="form-control">
            </select>
            <br />
            <label asp-for="IdUser" class="control-label">Usuario</label>
            <select asp-for="IdUser" asp-items="ViewBag.Users" class="form-control">
            </select>
            <br />
            <div class="form-group">
                <label asp-for="PriceOffer" class="control-label">Preço</label>
                <input asp-for="PriceOffer" class="form-control" />
                <span asp-validation-for="PriceOffer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dar lance" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Leilao/src/Leilao.UI.Site/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo</h1>
</div>

Leilao/src/Leilao.UI.Site/Views/Product/CreateProduct.cshtml
@model Leilao.ApplicationService.ViewModels.Request.Product.CreatePrductRequestViewModel

@{
    ViewData["Title"] = "Criação de Produtos";
}

<h1>Criação de Produtos</h1>

<h4>Crie os produtos para leiloar aqui</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateProduct">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Leilao/src/Leilao.UI.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MZ Leilao</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MZ Leilao</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="CreateProduct">Criar Produto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="CreateUser">Criar Usuario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="CreateBid">Dar Lance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="BidList">Lances</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MZ LEILAO
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Leilao/src/Leilao.UI.Site/Views/User/CreateUser.cshtml
@model Leilao.ApplicationService.ViewModels.Request.User.CreateUserRequestViewModel

@{
    ViewData["Title"] = "Criação de Usuario";
}

<h1>Criação de Usuario</h1>

<h4>Crie usuarios aqui</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}